//! Owns the `bladeink::Story` and turns it into a renderable scene.
//!
//! Two bladeink 2.0.0 constraints shape this module, both measured in the N0
//! spike rather than assumed:
//!
//! - **Choice tags do not populate.** `Choice::tags` is empty whatever the
//!   authoring syntax, so a choice cannot carry its authored id as a tag.
//!   Instead each ink branch assigns `chosen`, and the runtime reads it after
//!   the choice is taken. That binding is explicit and order-independent.
//! - **`tags_for_content_at_path` returns `Ok` for any path**, so it cannot
//!   test whether a knot exists. The knot list is generated by
//!   `add-ink-compiler` instead.

use bladeink::{story::Story, value_type::ValueType};
use serde::{Deserialize, Serialize};

use super::knot_for_beat;
use crate::game_data::story_beat_def;
use crate::generated_ink::{MAIN_INK_JSON, MAIN_INK_KNOTS};

/// Ink variable each choice branch assigns with its authored choice id.
const CHOSEN_VAR: &str = "chosen";
/// Ink variable carrying the simulation's seed, since ink has no Rust setter.
const SEED_VAR: &str = "ink_seed";

/// One line of dialogue with the presentation tags authored beside it.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct InkLine {
    pub text: String,
    /// Raw `key:value` tags: `speaker`, `mood`, `sfx`, `camera`.
    pub tags: Vec<String>,
}

/// One presented choice. `choice_id` is the authored content id whose effects
/// apply; `index` is what the player's command sends back.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct InkChoice {
    pub index: usize,
    pub text: String,
    pub choice_id: Option<String>,
}

/// Everything the browser needs to render an ink beat.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct InkScene {
    pub beat_id: String,
    pub lines: Vec<InkLine>,
    pub choices: Vec<InkChoice>,
}

/// Wraps the ink runtime. Not serializable and not `Send`: bladeink is
/// `Rc`-based, which is fine because the simulation runs on one thread, in a
/// Web Worker in the browser.
pub struct NarrativeStory {
    story: Story,
}

/// Is this beat rendered by ink? Beats without a knot render from their
/// authored `body`, so ink adoption proceeds beat by beat.
pub fn beat_has_knot(beat_id: &str) -> bool {
    MAIN_INK_KNOTS.contains(&knot_for_beat(beat_id).as_str())
}

impl NarrativeStory {
    pub fn new(seed: u64) -> Result<Self, String> {
        let mut story = Story::new(MAIN_INK_JSON).map_err(|error| format!("{error:?}"))?;
        // Ink has no Rust seed setter (N0 spike, Q3), so the seed crosses into
        // ink as a value. Clamping into i32 keeps ink's arithmetic defined.
        let ink_seed = (seed % (i32::MAX as u64)) as i32;
        story
            .set_variable(SEED_VAR, &ValueType::Int(ink_seed))
            .map_err(|error| format!("{error:?}"))?;
        Ok(Self { story })
    }

    /// Rebuild from serialized ink state. Falls back to a fresh story when the
    /// state cannot be loaded, so a save written by an older ink build still
    /// opens rather than bricking the run.
    pub fn from_state(seed: u64, ink_state: Option<&str>) -> Result<Self, String> {
        let mut narrative = Self::new(seed)?;
        if let Some(state) = ink_state {
            if narrative.story.load_state(state).is_err() {
                return Self::new(seed);
            }
        }
        Ok(narrative)
    }

    pub fn save_state(&self) -> Option<String> {
        self.story.save_state().ok()
    }

    /// Enter a beat's knot and collect everything up to its choices.
    pub fn enter_beat(&mut self, beat_id: &str) -> Result<InkScene, String> {
        self.set_chosen("");
        self.story
            .choose_path_string(&knot_for_beat(beat_id), true, None)
            .map_err(|error| format!("{error:?}"))?;
        self.collect(beat_id)
    }

    /// Take a presented choice. Returns the scene it produced and the authored
    /// choice id ink recorded, which the caller applies effects for.
    pub fn choose(&mut self, beat_id: &str, index: usize) -> Result<(InkScene, String), String> {
        if index >= self.story.get_current_choices().len() {
            return Err(format!("ink choice {index} is not presented"));
        }
        self.set_chosen("");
        self.story
            .choose_choice_index(index)
            .map_err(|error| format!("{error:?}"))?;
        let scene = self.collect(beat_id)?;
        let chosen = self.chosen();
        if chosen.is_empty() {
            return Err(format!(
                "ink choice {index} of {beat_id} set no `{CHOSEN_VAR}`; it would change nothing"
            ));
        }
        Ok((scene, chosen))
    }

    fn chosen(&self) -> String {
        match self.story.get_variable(CHOSEN_VAR) {
            Some(ValueType::String(value)) => value.string.clone(),
            _ => String::new(),
        }
    }

    fn set_chosen(&mut self, value: &str) {
        let _ = self
            .story
            .set_variable(CHOSEN_VAR, &ValueType::new::<&str>(value));
    }

    fn collect(&mut self, beat_id: &str) -> Result<InkScene, String> {
        let mut lines = Vec::new();
        while self.story.can_continue() {
            let text = self.story.cont().map_err(|error| format!("{error:?}"))?;
            let tags = self
                .story
                .get_current_tags()
                .map_err(|error| format!("{error:?}"))?;
            let text = text.trim().to_string();
            if !text.is_empty() {
                lines.push(InkLine { text, tags });
            }
        }

        // Presentation ids come from the authored catalog by position; the
        // `chosen` binding verifies that position at choose time, so a
        // reordered ink file fails loudly instead of applying wrong effects.
        let authored = story_beat_def(beat_id).map(|beat| beat.choices).unwrap_or(&[]);
        let choices = self
            .story
            .get_current_choices()
            .iter()
            .enumerate()
            .map(|(index, choice)| InkChoice {
                index,
                text: choice.text.trim().to_string(),
                choice_id: authored.get(index).map(|c| c.id.to_string()),
            })
            .collect();

        Ok(InkScene {
            beat_id: beat_id.to_string(),
            lines,
            choices,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const BEAT: &str = "story.beat.first_glimpse";

    #[test]
    fn entering_a_beat_yields_its_prose_tags_and_choices() {
        let mut narrative = NarrativeStory::new(7).expect("story loads");
        let scene = narrative.enter_beat(BEAT).expect("beat entered");

        assert_eq!(scene.beat_id, BEAT);
        assert_eq!(scene.lines.len(), 1);
        assert!(scene.lines[0].text.starts_with("From the ridge"));
        assert!(scene.lines[0].tags.contains(&"speaker:narrator".to_string()));
        assert!(scene.lines[0].tags.contains(&"mood:tense".to_string()));

        assert_eq!(scene.choices.len(), 2);
        assert_eq!(scene.choices[0].text, "Study the lights");
        assert_eq!(
            scene.choices[0].choice_id.as_deref(),
            Some("story.choice.glimpse.watch_lights")
        );
    }

    #[test]
    fn choosing_returns_the_authored_choice_id_and_its_response() {
        let mut narrative = NarrativeStory::new(7).expect("story loads");
        narrative.enter_beat(BEAT).expect("beat entered");
        let (scene, chosen) = narrative.choose(BEAT, 0).expect("choice taken");

        assert_eq!(chosen, "story.choice.glimpse.watch_lights");
        assert!(scene.choices.is_empty());
        assert!(scene.lines.iter().any(|line| line.text.contains("hum")));
    }

    #[test]
    fn presented_choice_ids_agree_with_what_ink_records() {
        // The contract that makes positional presentation safe: for every ink
        // choice, the id shown before choosing is the id ink sets after. A
        // reordered or renamed ink choice fails here rather than silently
        // applying another choice's effects.
        let authored = story_beat_def(BEAT).expect("beat exists").choices;
        for index in 0..authored.len() {
            let mut narrative = NarrativeStory::new(1).expect("story loads");
            let scene = narrative.enter_beat(BEAT).expect("beat entered");
            let presented = scene.choices[index]
                .choice_id
                .clone()
                .expect("presented choice has an id");
            let (_, recorded) = narrative.choose(BEAT, index).expect("choice taken");
            assert_eq!(
                presented, recorded,
                "ink choice {index} of {BEAT} presents {presented} but records {recorded}",
            );
            assert!(
                authored.iter().any(|c| c.id == recorded),
                "{recorded} is not an authored choice of {BEAT}",
            );
        }
    }

    #[test]
    fn ink_state_round_trips_through_a_save() {
        let mut narrative = NarrativeStory::new(3).expect("story loads");
        narrative.enter_beat(BEAT).expect("beat entered");
        let saved = narrative.save_state().expect("state saves");

        let mut reloaded = NarrativeStory::from_state(3, Some(&saved)).expect("state loads");
        let (scene, chosen) = reloaded.choose(BEAT, 1).expect("choice taken after reload");
        assert_eq!(chosen, "story.choice.glimpse.scan_ruins");
        assert!(
            scene
                .lines
                .iter()
                .any(|line| line.text.contains("center still breathes"))
        );
    }

    #[test]
    fn a_corrupt_ink_state_falls_back_to_a_fresh_story() {
        let mut narrative =
            NarrativeStory::from_state(3, Some("{not valid ink state")).expect("falls back");
        let scene = narrative.enter_beat(BEAT).expect("beat still entered");
        assert_eq!(scene.choices.len(), 2);
    }

    #[test]
    fn an_unpresented_choice_index_is_refused() {
        let mut narrative = NarrativeStory::new(1).expect("story loads");
        narrative.enter_beat(BEAT).expect("beat entered");
        assert!(narrative.choose(BEAT, 9).is_err());
    }

    #[test]
    fn only_authored_knots_report_as_ink_backed() {
        assert!(beat_has_knot(BEAT));
        assert!(!beat_has_knot("story.beat.road_to_base"));
        assert!(!beat_has_knot("story.beat.does_not_exist"));
    }

    #[test]
    fn every_ink_knot_names_a_real_story_beat() {
        // A knot whose beat does not exist is prose the game can never show.
        for knot in MAIN_INK_KNOTS {
            let beat_id = knot.replacen("story_beat_", "story.beat.", 1);
            assert!(
                story_beat_def(&beat_id).is_some(),
                "ink knot {knot} has no story beat {beat_id}",
            );
        }
    }
}
