//! Compile authored `.ink` into the generated Rust constant `add-core` embeds.
//!
//! Host-only by design: `bladeink-compiler` must never reach the browser WASM,
//! so compilation happens here at build time and the runtime loads JSON.
//!
//!   add-ink-compiler <out.rs> <in.ink>...
//!   add-ink-compiler --check <out.rs> <in.ink>...

use std::{fs, path::Path, process::ExitCode};

use bladeink_compiler::Compiler;

const BANNER: &str = "\
// @generated by `npm run content:build` from packages/add-content/narrative/story/.
// Do not edit by hand; edit the .ink source and re-run the generator.
";

fn render(sources: &[String]) -> Result<String, String> {
    let mut out = String::from(BANNER);
    for path in sources {
        let stem = Path::new(path)
            .file_stem()
            .and_then(|s| s.to_str())
            .ok_or_else(|| format!("bad ink path: {path}"))?;
        let source = fs::read_to_string(path).map_err(|e| format!("{path}: {e}"))?;
        let json = Compiler::new()
            .compile(&source)
            .map_err(|e| format!("{path}: {e:?}"))?;
        let ident = stem.to_uppercase().replace(['-', '.'], "_");
        // Knot names are emitted alongside the JSON so the runtime can answer
        // "is this beat ink-backed?" from a generated fact rather than by
        // probing the story and disturbing its pointer.
        let mut knots: Vec<&str> = source
            .lines()
            .filter_map(|line| line.trim().strip_prefix("==="))
            .map(|rest| rest.trim_matches(|c: char| c == '=' || c.is_whitespace()))
            .filter(|name| !name.is_empty())
            .collect();
        knots.sort_unstable();
        knots.dedup();
        let knot_list = knots
            .iter()
            .map(|k| format!("\"{k}\""))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "\n/// Compiled from `{path}`.\npub const {ident}_INK_JSON: &str = r##\"{json}\"##;\n\n\
             /// Knots declared in `{path}`.\npub const {ident}_INK_KNOTS: &[&str] = &[{knot_list}];\n"
        ));
    }
    Ok(out)
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let check = args.first().map(|a| a == "--check").unwrap_or(false);
    let args = if check { &args[1..] } else { &args[..] };

    let Some((out_path, sources)) = args.split_first() else {
        eprintln!("usage: add-ink-compiler [--check] <out.rs> <in.ink>...");
        return ExitCode::FAILURE;
    };

    let rendered = match render(sources) {
        Ok(text) => text,
        Err(message) => {
            eprintln!("[ink:build] {message}");
            return ExitCode::FAILURE;
        }
    };

    let current = fs::read_to_string(out_path).unwrap_or_default();
    if current == rendered {
        if !check {
            println!("[ink:build] up to date: {out_path}");
        }
        return ExitCode::SUCCESS;
    }
    if check {
        eprintln!("[ink:check] DRIFT: {out_path} is out of date with its .ink source");
        eprintln!("[ink:check] run `npm run content:build`.");
        return ExitCode::FAILURE;
    }
    if let Some(parent) = Path::new(out_path).parent() {
        let _ = fs::create_dir_all(parent);
    }
    match fs::write(out_path, rendered) {
        Ok(()) => {
            println!("[ink:build] wrote {out_path}");
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("[ink:build] {out_path}: {e}");
            ExitCode::FAILURE
        }
    }
}
