// @generated by `npm run content:build` from packages/add-content/src/content/cinematics.ts.
// Do not edit by hand; edit the TS source and re-run the generator.

use crate::game_data::*;

pub(in crate::game_data) const CINEMATICS: &[CinematicDef] = &[CinematicDef {
    id: "cinematic.sample",
    label: "Sample moment",
    skippable: true,
    freeze_world: true,
    replay: CinematicReplayKind::Once,
    beats: &[
        CinematicBeatDef {
            id: "cinematic.sample.beat.title",
            media: CinematicMediaKind::Text,
            asset_id: "",
            copy: "A beat of type.",
            advance: CinematicAdvanceKind::Auto,
            seconds: 2.0,
        },
        CinematicBeatDef {
            id: "cinematic.sample.beat.still",
            media: CinematicMediaKind::Image,
            asset_id: "sample/still",
            copy: "A still, with a caption.",
            advance: CinematicAdvanceKind::Input,
            seconds: 0.0,
        },
        CinematicBeatDef {
            id: "cinematic.sample.beat.clip",
            media: CinematicMediaKind::Video,
            asset_id: "sample/clip",
            copy: "",
            advance: CinematicAdvanceKind::MediaEnd,
            seconds: 30.0,
        },
    ],
}];
