// @generated by `npm run content:build` from packages/add-domain/src/content/creatures.ts.
// Do not edit by hand; edit the TS source and re-run the generator.

use crate::game_data::*;

pub(in crate::game_data) const CREATURES: &[CreatureDef] = &[
    CreatureDef {
        id: "rat",
        label: "Rat",
        hp: 8.0,
        attack: 1.2,
        threat: 0.15,
        xp_reward: 6.0,
    },
    CreatureDef {
        id: "giant_rat",
        label: "Giant Rat",
        hp: 20.0,
        attack: 3.0,
        threat: 0.4,
        xp_reward: 16.0,
    },
];
