// @generated by `npm run content:build` from packages/add-content/src/content/narrative-entities.ts.
// Do not edit by hand; edit the TS source and re-run the generator.

use crate::game_data::*;

pub(in crate::game_data) const NARRATIVE_ENTITIES: &[NarrativeEntityDef] = &[
    NarrativeEntityDef {
        id: "entity.sleepless",
        label: "Sleepless in Decibels",
        kind: GroupKind::SurvivalFaction,
        parent: None,
        rank: 0,
        influence: 0.0,
        values: &[
            ("security", 0.9000),
            ("benevolence", 0.6000),
            ("conformity", 0.4000),
            ("universalism", -0.7000),
            ("stimulation", -0.5000),
        ],
    },
    NarrativeEntityDef {
        id: "entity.sleepless.sounding_five",
        label: "The Sounding Five",
        kind: GroupKind::Crew,
        parent: Some("entity.sleepless"),
        rank: 3,
        influence: 0.6,
        values: &[],
    },
    NarrativeEntityDef {
        id: "entity.vell",
        label: "David Chen",
        kind: GroupKind::Individual,
        parent: Some("entity.sleepless.sounding_five"),
        rank: 3,
        influence: 0.7,
        values: &[],
    },
    NarrativeEntityDef {
        id: "entity.joren",
        label: "Kaylee Lindquist",
        kind: GroupKind::Individual,
        parent: Some("entity.sleepless.sounding_five"),
        rank: 1,
        influence: 0.3,
        values: &[
            ("stimulation", 0.9000),
            ("hedonism", 0.7000),
            ("self_direction", 0.5000),
            ("conformity", -0.8000),
            ("security", -0.6000),
        ],
    },
];
