// @generated by `npm run content:build` from packages/add-content/src/content/narrative-acts.ts.
// Do not edit by hand; edit the TS source and re-run the generator.

use crate::game_data::*;

pub(in crate::game_data) const NARRATIVE_ACTS: &[NarrativeActDef] = &[
    NarrativeActDef {
        id: "act.share_scarce_water",
        label: "Share scarce water",
        intent: "deliberate",
        impacts: &[
            ActImpactDef {
                scope: "Target",
                axis: "goodwill",
                tier: "major",
                sign: 1,
            },
            ActImpactDef {
                scope: "Target",
                axis: "debt",
                tier: "moderate",
                sign: 1,
            },
            ActImpactDef {
                scope: "ParentOf(Target)",
                axis: "goodwill",
                tier: "moderate",
                sign: 1,
            },
            ActImpactDef {
                scope: "FactionOf(Target)",
                axis: "alignment",
                tier: "minor",
                sign: 1,
            },
        ],
    },
    NarrativeActDef {
        id: "act.clear_nearby_threat",
        label: "Clear a nearby threat",
        intent: "deliberate",
        impacts: &[
            ActImpactDef {
                scope: "Target",
                axis: "competence",
                tier: "moderate",
                sign: 1,
            },
            ActImpactDef {
                scope: "ParentOf(Target)",
                axis: "competence",
                tier: "moderate",
                sign: 1,
            },
            ActImpactDef {
                scope: "ParentOf(Target)",
                axis: "dependence",
                tier: "minor",
                sign: 1,
            },
            ActImpactDef {
                scope: "FactionOf(Target)",
                axis: "competence",
                tier: "minor",
                sign: 1,
            },
        ],
    },
    NarrativeActDef {
        id: "act.break_a_promise",
        label: "Break a promise",
        intent: "deliberate",
        impacts: &[
            ActImpactDef {
                scope: "Target",
                axis: "integrity",
                tier: "major",
                sign: -1,
            },
            ActImpactDef {
                scope: "Target",
                axis: "grievance",
                tier: "moderate",
                sign: 1,
            },
            ActImpactDef {
                scope: "ParentOf(Target)",
                axis: "integrity",
                tier: "minor",
                sign: -1,
            },
        ],
    },
];
