// @generated by `npm run content:build` from packages/add-content/src/content/narrative-acts.ts.
// Do not edit by hand; edit the TS source and re-run the generator.

use crate::game_data::*;

pub(in crate::game_data) const NARRATIVE_ACTS: &[NarrativeActDef] = &[
    NarrativeActDef {
        id: "act.share_scarce_water",
        label: "Share scarce water",
        kinds: &["aid", "generosity"],
        intent: "deliberate",
        expresses: &[("universalism", 1.0000)],
        secrecy: "witnessed",
        impacts: &[
            ActImpactDef {
                scope: "Target",
                axis: "goodwill",
                tier: "major",
                sign: 1,
            },
            ActImpactDef {
                scope: "Target",
                axis: "debt",
                tier: "moderate",
                sign: 1,
            },
            ActImpactDef {
                scope: "ParentOf(Target)",
                axis: "goodwill",
                tier: "moderate",
                sign: 1,
            },
            ActImpactDef {
                scope: "FactionOf(Target)",
                axis: "alignment",
                tier: "moderate",
                sign: 0,
            },
        ],
    },
    NarrativeActDef {
        id: "act.clear_nearby_threat",
        label: "Clear a nearby threat",
        kinds: &["aid", "violence"],
        intent: "deliberate",
        expresses: &[("security", 0.6000), ("benevolence", 0.4000)],
        secrecy: "public",
        impacts: &[
            ActImpactDef {
                scope: "Target",
                axis: "competence",
                tier: "moderate",
                sign: 1,
            },
            ActImpactDef {
                scope: "ParentOf(Target)",
                axis: "competence",
                tier: "moderate",
                sign: 1,
            },
            ActImpactDef {
                scope: "ParentOf(Target)",
                axis: "dependence",
                tier: "minor",
                sign: 1,
            },
            ActImpactDef {
                scope: "FactionOf(Target)",
                axis: "competence",
                tier: "minor",
                sign: 1,
            },
        ],
    },
    NarrativeActDef {
        id: "act.spare_a_life",
        label: "Spare a life",
        kinds: &["mercy"],
        intent: "deliberate",
        expresses: &[("benevolence", 0.7000), ("universalism", 0.3000)],
        secrecy: "witnessed",
        impacts: &[
            ActImpactDef {
                scope: "Target",
                axis: "goodwill",
                tier: "severe",
                sign: 1,
            },
            ActImpactDef {
                scope: "Target",
                axis: "debt",
                tier: "major",
                sign: 1,
            },
            ActImpactDef {
                scope: "ParentOf(Target)",
                axis: "alignment",
                tier: "moderate",
                sign: 0,
            },
        ],
    },
    NarrativeActDef {
        id: "act.aid_the_hero",
        label: "Aid the Hero",
        kinds: &["aid"],
        intent: "deliberate",
        expresses: &[("benevolence", 1.0000)],
        secrecy: "witnessed",
        impacts: &[
            ActImpactDef {
                scope: "Target",
                axis: "debt",
                tier: "moderate",
                sign: -1,
            },
            ActImpactDef {
                scope: "Target",
                axis: "closeness",
                tier: "moderate",
                sign: 1,
            },
        ],
    },
    NarrativeActDef {
        id: "act.denounce",
        label: "Denounce the Hero",
        kinds: &["denunciation"],
        intent: "deliberate",
        expresses: &[("conformity", 0.6000), ("security", 0.4000)],
        secrecy: "public",
        impacts: &[
            ActImpactDef {
                scope: "Target",
                axis: "integrity",
                tier: "moderate",
                sign: -1,
            },
            ActImpactDef {
                scope: "Target",
                axis: "goodwill",
                tier: "minor",
                sign: -1,
            },
        ],
    },
    NarrativeActDef {
        id: "act.swear_an_oath",
        label: "Swear an oath",
        kinds: &["oath"],
        intent: "deliberate",
        expresses: &[("tradition", 0.5000), ("conformity", 0.5000)],
        secrecy: "public",
        impacts: &[ActImpactDef {
            scope: "Target",
            axis: "closeness",
            tier: "minor",
            sign: 1,
        }],
    },
    NarrativeActDef {
        id: "act.break_a_promise",
        label: "Break a promise",
        kinds: &["forbidden", "harm"],
        intent: "deliberate",
        expresses: &[],
        secrecy: "witnessed",
        impacts: &[
            ActImpactDef {
                scope: "Target",
                axis: "integrity",
                tier: "major",
                sign: -1,
            },
            ActImpactDef {
                scope: "Target",
                axis: "grievance",
                tier: "moderate",
                sign: 1,
            },
            ActImpactDef {
                scope: "ParentOf(Target)",
                axis: "integrity",
                tier: "minor",
                sign: -1,
            },
        ],
    },
];
