// @generated by `npm run content:build` from packages/add-domain/src/content/objectives.ts.
// Do not edit by hand; edit the TS source and re-run the generator.

use crate::game_data::*;

pub(in crate::game_data) const OBJECTIVES: &[ObjectiveDef] = &[
    ObjectiveDef {
        id: "objective.restore_studio",
        label: "Restore the Studio",
        description: "Repair the Studio so it can anchor the base.",
        sequence: 1,
        conditions: &[Condition::FlagSet(FLAG_BASE_STUDIO_RESTORED)],
        rewards: &[EffectDef::Note {
            text: "Objective complete: the Studio stands again.",
        }],
    },
    ObjectiveDef {
        id: "objective.build_fire_pit",
        label: "Build the Fire Pit",
        description: "Raise morale by lighting the Fire Pit.",
        sequence: 2,
        conditions: &[Condition::FlagSet(FLAG_BASE_FIRE_PIT_BUILT)],
        rewards: &[EffectDef::Note {
            text: "Objective complete: the Fire Pit is lit.",
        }],
    },
    ObjectiveDef {
        id: "objective.reach_ring_3",
        label: "Expand the Bubble to Ring 3",
        description:
            "Stabilize the field out to the third ring, within reach of the Survivor Cave.",
        sequence: 3,
        conditions: &[Condition::BubbleReachAtLeast(3)],
        rewards: &[
            EffectDef::Note {
                text: "Objective complete: the bubble reaches the cave's range.",
            },
            EffectDef::GrantResource {
                resource_id: "resource.vibes",
                amount: 25.0,
            },
        ],
    },
    ObjectiveDef {
        id: "objective.first_recruit",
        label: "Recruit a Survivor",
        description: "Bring the first survivor home from the cave.",
        sequence: 4,
        conditions: &[Condition::RecruitedAny],
        rewards: &[EffectDef::Note {
            text: "Objective complete: you are no longer alone.",
        }],
    },
];
