// @generated by `npm run content:build` from packages/add-content/src/content/narrative-reactions.ts.
// Do not edit by hand; edit the TS source and re-run the generator.

use crate::game_data::*;

pub(in crate::game_data) const REACTIONS: &[ReactionDef] = &[ReactionDef {
    id: "reaction.vell_denounces_a_broken_promise",
    label: "Vell denounces a broken promise",
    when_act: "act.break_a_promise",
    actor: "entity.vell",
    after_days: 1.0,
    emit_act: "act.denounce",
    emit_target: "entity.sleepless.sounding_five",
    cooldown_days: 30.0,
}];
