// @generated by `npm run content:build` from packages/add-content/src/content/narrative-patterns.ts.
// Do not edit by hand; edit the TS source and re-run the generator.

use crate::game_data::*;

pub(in crate::game_data) const SIFT_PATTERNS: &[SiftPatternDef] = &[
    SiftPatternDef {
        id: "arc.mercy_repaid",
        label: "Mercy repaid",
        first_kind: "mercy",
        second_kind: "aid",
        min_gap_days: 2.0,
        expires_after_days: 90.0,
        requires_cause: true,
    },
    SiftPatternDef {
        id: "arc.broken_oath",
        label: "Broken oath",
        first_kind: "oath",
        second_kind: "forbidden",
        min_gap_days: 0.0,
        expires_after_days: 365.0,
        requires_cause: false,
    },
];
