// @generated by `npm run content:build` from packages/add-content/src/content/narrative-storylets.ts.
// Do not edit by hand; edit the TS source and re-run the generator.

use crate::game_data::*;

pub(in crate::game_data) const STORYLETS: &[StoryletDef] = &[
    StoryletDef {
        id: "storylet.two_survivors_talk",
        knot: "sl_two_survivors_talk",
        roles: &[
            StoryletRoleDef {
                name: "x",
                axis: "",
                at_least: "very_low",
                at_most: "very_high",
            },
            StoryletRoleDef {
                name: "y",
                axis: "",
                at_least: "very_low",
                at_most: "very_high",
            },
        ],
        base_salience: 10,
        cooldown_days: 2.0,
        trigger_arc: "",
    },
    StoryletDef {
        id: "storylet.wronged_and_witness",
        knot: "sl_wronged_and_witness",
        roles: &[
            StoryletRoleDef {
                name: "x",
                axis: "integrity",
                at_least: "very_low",
                at_most: "low",
            },
            StoryletRoleDef {
                name: "y",
                axis: "",
                at_least: "very_low",
                at_most: "very_high",
            },
        ],
        base_salience: 40,
        cooldown_days: 5.0,
        trigger_arc: "arc.broken_oath",
    },
];
