// @generated by `npm run content:build` from packages/add-content/src/content/content-version.ts.
// Do not edit by hand; edit the TS source and re-run the generator.

pub const CONTENT_SCHEMA_VERSION: u16 = 1;
pub const CONTENT_CATALOG_VERSION: u16 = 1;
pub const CONTENT_SAVE_SCHEMA_VERSION: u16 = 15;
