#!/usr/bin/env python3
"""Generate a conservative inventory of lore pages needing editorial cleanup."""
from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LORE = ROOT / "lore"
OUTPUT = LORE / "WORK_PAGES.md"

CONTROL_NAMES = {
    "LORE_REVISION_v2.md": "canon revision log",
    "Lore_todo.md": "open editorial task list",
    "progress_report.md": "progress report",
    "pages-to-create.md": "missing-page inventory",
}
SIGNALS = {
    "revision": re.compile(r"PARTIALLY IMPLEMENTED|WHAT REMAINS|NEXT STEPS|CORE CHANGES|revision|tightening", re.I),
    "todo": re.compile(r"\bTODO\b|\bTBD\b|next steps|remaining tasks|to be written|to be completed", re.I),
    "draft": re.compile(r"status\s*[:=]\s*(draft|planned|unknown)|\bDRAFT\b|\bPLANNED\b", re.I),
    "template": re.compile(r"template|placeholder|fill in", re.I),
}


def first_match(text: str, pattern: re.Pattern[str]) -> str:
    for line in text.splitlines():
        if pattern.search(line):
            value = " ".join(line.strip().split())[:180]
            value = re.sub(r"\[([^]]+)\]\([^)]*\)", r"\1", value)
            value = value.replace("`", "")
            return value
    return "explicit filename signal"


def main() -> int:
    categories: dict[str, dict[str, str]] = defaultdict(dict)
    all_pages = sorted(LORE.rglob("*.md"))
    for path in all_pages:
        if ".vitepress" in path.parts or path.name == OUTPUT.name:
            continue
        rel = path.relative_to(LORE).as_posix()
        text = path.read_text(encoding="utf-8", errors="replace")
        if path.name in CONTROL_NAMES:
            categories["Control and revision documents"][rel] = CONTROL_NAMES[path.name]
        if path.name == "index.md":
            categories["Generated indexes to review"][rel] = "generated navigation page"
        if "telegram_archives" in path.parts:
            categories["Archives to review separately"][rel] = "archive material, not editorial canon"
        if "template" in path.name.lower() or "template" in text.lower():
            categories["Templates and vocabularies"][rel] = first_match(text, SIGNALS["template"])
        for name in ("revision", "todo", "draft"):
            if SIGNALS[name].search(text):
                label = {
                    "revision": "explicit revision or open decision language",
                    "todo": "explicit unfinished-work language",
                    "draft": "explicit draft/planned status",
                }[name]
                categories[f"Pages with {name} signals"][rel] = first_match(text, SIGNALS[name])

    lines = [
        "# Lore pages for editorial cleanup",
        "",
        "> Generated by `npm run lore:work-inventory`. This is a work queue, not canon.",
        "> No page is deleted or downgraded automatically. Review each category before changing status.",
        "",
        "## How to use this inventory",
        "",
        "1. Start with **Control and revision documents**. Decide what is current canon, historical decision, or obsolete proposal.",
        "2. Review pages with **revision**, **todo** or **draft** signals and rewrite them with the encyclopedic lore-writing skill.",
        "3. Treat **Templates and vocabularies** as authoring tools, not encyclopedia articles.",
        "4. Review **Generated indexes** only for navigation. Their content comes from the source tree.",
        "5. Review Telegram **archives separately**. Do not apply encyclopedic prose to raw testimony before preserving its provenance.",
        "",
    ]
    for title in sorted(categories):
        entries = categories[title]
        lines.extend([f"## {title} ({len(entries)})", ""])
        for rel, reason in sorted(entries.items()):
            lines.append(f"- `{rel}`: {reason}")
        lines.append("")
    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")
    for title in sorted(categories):
        print(f"{title}: {len(categories[title])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
